version: '3.1'
services:
  sentinel:
    image: registry.cn-beijing.aliyuncs.com/potatoblog/sentinel
    restart: always
    container_name: sentinel
    ports:
      - 8070:8070
    networks:
      - mogu

networks:
  mogu:
    external: true
